using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;
internal static class DeviceDiagnostics {
 internal static string CleanName(string name){if(string.IsNullOrWhiteSpace(name))return "unavailable";name=Regex.Replace(name,@"[0-9a-f]{6,}","[id]",RegexOptions.IgnoreCase);name=Regex.Replace(name,@"(?:[0-9a-f]{2}[:-]){5}[0-9a-f]{2}","[address]",RegexOptions.IgnoreCase);name=Regex.Replace(name,@"[\r\n\t\x00-\x1f]"," ");return name.Length>100?name.Substring(0,100):name;}
 internal static string Reason(Device d){if(d.Type!=2)return "not-HID";if(d.Vid!=0x28de)return "other-vendor";if(d.Pid<0x1302 || d.Pid>0x1305)return "unsupported-PID (not SC2 1302/1303/1304/1305)";if(d.Page!=0xff00 || d.Usage!=1)return "different-HID-collection (requires FF00:0001)";return "eligible (user must select device)";}
 static string Name(Device d){try{using(var h=CreateFile(d.Path,0,3,IntPtr.Zero,3,0,IntPtr.Zero)){if(!h.IsInvalid){var b=new byte[256];if(HidD_GetProductString(h,b,b.Length)){string n=Encoding.Unicode.GetString(b).TrimEnd('\0');if(!string.IsNullOrWhiteSpace(n))return CleanName(n);}}}}catch{}return d.Vid==0x28de?CleanName(DeviceGate.FriendlyName(d.Path)):"unavailable";}
 internal static void Write(string file,IEnumerable<Device> devices){var text=new StringBuilder();text.AppendLine("Talaria device diagnostics · "+DateTime.UtcNow.ToString("o"));text.AppendLine("Version="+typeof(DeviceDiagnostics).Assembly.GetName().Version+" OS="+Environment.OSVersion.Version+" x64="+Environment.Is64BitOperatingSystem);text.AppendLine("Source=Windows Raw Input + SetupAPI HID interfaces (Valve candidates). Filter=HID VID 28DE PID 1302/1303/1304/1305 Usage FF00:0001. Names do not affect matching.");text.AppendLine("Device paths, addresses and input reports omitted. Product/display names may be user-customized.");int total=0,hid=0,eligible=0;foreach(var d in devices){total++;if(d.Type!=2)continue;hid++;if(DeviceGate.IsSc2(d.Type,d.Vid,d.Pid,d.Page,d.Usage))eligible++;text.AppendLine(string.Format("HID #{0}: name={1}; VID={2:X4}; PID={3:X4}; Usage={4:X4}:{5:X4}; transport={7}; source={8}; state={9}; result={6}",hid,Name(d),d.Vid,d.Pid,d.Page,d.Usage,Reason(d),DeviceGate.Transport(d.Pid,d.Path),d.Source,d.State));}text.AppendLine("Total="+total+" HID="+hid+" eligible="+eligible+" unreadable="+Devices.ReadFailures+" HID-enumeration-failures="+HidDiscovery.Failed);if(eligible==0)text.AppendLine("No eligible Raw Input or HID collection. This does not prove that the controller is disconnected; check connection mode and HID enumeration.");File.WriteAllText(file,text.ToString(),new UTF8Encoding(true));}
 internal static void Test(){if(Reason(new Device{Type=2,Vid=0x28de,Pid=0x1205,Page=0xff00,Usage=1}).StartsWith("eligible"))throw new Exception("Diagnostic widened device gate");if(!Reason(new Device{Type=2,Vid=0x28de,Pid=0x1303,Page=0xff00,Usage=1}).StartsWith("eligible"))throw new Exception("Diagnostic mismatch");string n=CleanName("Steam Ctrl (BT) FXA99624006AE\nAA:BB:CC:DD:EE:FF");if(n.Contains("99624006") || n.Contains("AA:BB") || n.Contains("\n"))throw new Exception("Device name redaction failed");}
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern SafeFileHandle CreateFile(string path,uint access,uint share,IntPtr security,uint creation,uint flags,IntPtr template);
 [DllImport("hid.dll",SetLastError=true)]static extern bool HidD_GetProductString(SafeFileHandle h,byte[] text,int length);
}
