using System;
internal static class DeviceGate {
 internal static bool IsSc2(uint type,uint vid,uint pid,ushort page,ushort usage){return type==2 && vid==0x28de && (pid==0x1302 || pid==0x1303 || pid==0x1304 || pid==0x1305) && page==0xff00 && usage==1;}
 // Transport detection follows SteamlessController; HID path precedes PID.
 internal static string Transport(uint pid,string path){string p=(path??"").ToLowerInvariant();if(p.Contains("{00001812-0000-1000-8000-00805f9b34fb}") || p.Contains("bthledevice") || p.Contains("bthenum"))return "bluetooth";if(pid==0x1304 || pid==0x1305)return "receiver";if(pid==0x1302 || pid==0x1303)return "usb";return "unknown";}
 internal static bool HapticsEligible(Device d){return d!=null && IsSc2(d.Type,d.Vid,d.Pid,d.Page,d.Usage) && !string.IsNullOrWhiteSpace(d.Path) && Transport(d.Pid,d.Path)!="unknown";}
 internal static bool VerifiedBle(Device d){return d!=null && IsSc2(d.Type,d.Vid,d.Pid,d.Page,d.Usage) && d.Pid==0x1303 && Transport(d.Pid,d.Path)=="bluetooth";}
 internal static bool FirmwareKeyboardControl(Device d){return VerifiedBle(d) || (d!=null && IsSc2(d.Type,d.Vid,d.Pid,d.Page,d.Usage) && ((d.Pid==0x1302 && Transport(d.Pid,d.Path)=="usb") || ((d.Pid==0x1304 || d.Pid==0x1305) && Transport(d.Pid,d.Path)=="receiver")));}
 internal static bool Allows(uint type,uint vid,uint pid,ushort page,ushort usage,string path,string selected){return IsSc2(type,vid,pid,page,usage) && !string.IsNullOrWhiteSpace(selected) && string.Equals(path,selected,StringComparison.OrdinalIgnoreCase);}
 internal static void Test(){foreach(uint p in new uint[]{0x1302,0x1304,0x1305})if(!FirmwareKeyboardControl(new Device{Type=2,Vid=0x28de,Pid=p,Page=0xff00,Usage=1,Path="hid#device"}))throw new Exception("USB/receiver firmware eligibility");if(FirmwareKeyboardControl(new Device{Type=2,Vid=0x28de,Pid=0x1304,Page=1,Usage=6,Path="hid#keyboard"}))throw new Exception("Keyboard collection allowed firmware commands");foreach(uint pid in new uint[]{0x1302,0x1303,0x1304,0x1305}){if(!Allows(2,0x28de,pid,0xff00,1,"selected","selected"))throw new Exception("SC2 transport rejected");if(Allows(2,0x28de,pid,0xff00,1,"empty-slot","selected"))throw new Exception("Receiver slot isolation lost");}if(Transport(0x1303,"HID#{00001812-0000-1000-8000-00805f9b34fb}")!="bluetooth" || Transport(0x1303,"hid#vid_28de&pid_1303")!="usb" || Transport(0x1304,"hid#pid_1304")!="receiver")throw new Exception("Transport classification");if(VerifiedBle(new Device{Type=2,Vid=0x28de,Pid=0x1302,Page=0xff00,Usage=1,Path="USB"}))throw new Exception("Unverified transport allowed feature writes");if(!Allows(2,0x28de,0x1303,0xff00,1,"ble-A","BLE-a"))throw new Exception("Selected SC2 rejected");if(Allows(2,0x28de,0x1303,0xff00,1,"ble-B","ble-A") || Allows(2,0x28de,0x1303,0xff00,1,"ble-A","") || Allows(2,0x28de,0x1205,0xff00,1,"deck","deck") || Allows(2,0x28de,0x11ff,0xff00,1,"virtual","virtual") || Allows(2,0x045e,0x028e,1,5,"moonlight","moonlight") || Allows(2,0x28de,0x1303,1,5,"pad","pad"))throw new Exception("Device isolation failed");}
 internal static string FriendlyName(string path){var m=System.Text.RegularExpressions.Regex.Match(path,@"_([0-9a-f]{12})(?:&|#)",System.Text.RegularExpressions.RegexOptions.IgnoreCase);if(m.Success)try{using(var device=Microsoft.Win32.Registry.LocalMachine.OpenSubKey(@"SYSTEM\CurrentControlSet\Enum\BTHLE\DEV_"+m.Groups[1].Value)){if(device!=null)foreach(string instance in device.GetSubKeyNames())using(var key=device.OpenSubKey(instance)){string name=key.GetValue("FriendlyName") as string;if(!string.IsNullOrWhiteSpace(name))return name;}}}catch(System.Security.SecurityException){}catch(UnauthorizedAccessException){}return "Steam Controller"+(m.Success?" · "+m.Groups[1].Value.Substring(6):"");}
}
