using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

internal sealed partial class PadHop {
 string editingAppPath;ComboBox scopeChoice;bool scopeLoading;StackPanel appsList;
 sealed class ScopeChoice{internal string Path;internal string Label;public override string ToString(){return Label;}}
 AppAssignment EditingApp(){return full.Apps.Find(a=>string.Equals(a.Path,editingAppPath,StringComparison.OrdinalIgnoreCase));}
 PadBook ContextApplied(){var a=EditingApp();return a==null?full.Applied:a.Applied??full.Applied;}
 string ContextName(){var a=EditingApp();return a==null?full.AppliedName:a.Applied==null?L.T("全局 · ")+full.AppliedName:a.AppliedName;}
 void BuildApplications(){var page=Get<StackPanel>("AppsPage");var card=Card(page,L.T("应用与游戏"));Hint(card,L.T("单独配置按键、触摸板和触觉。没有单独应用配置时使用全局；导入和编辑不会改变黑白名单。"));var header=new WrapPanel();card.Children.Add(header);Btn(header,L.T("＋ 导入应用／游戏"),delegate{var d=new Microsoft.Win32.OpenFileDialog{Filter=L.T("应用或快捷方式|*.exe;*.lnk"),Multiselect=true};if(d.ShowDialog(window)==true)ImportAppProfiles(d.FileNames);});var drop=new Border{Background=new SolidColorBrush(Color.FromRgb(19,32,43)),BorderBrush=new SolidColorBrush(Color.FromRgb(55,84,107)),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(5),Padding=new Thickness(20),Margin=new Thickness(0,12,0,12),AllowDrop=true,Child=new TextBlock{Text=L.T("拖入 EXE 或快捷方式，添加独立配置"),Foreground=Brushes.LightBlue}};card.Children.Add(drop);drop.DragOver+=delegate(object sender,DragEventArgs e){e.Effects=e.Data.GetDataPresent(DataFormats.FileDrop)?DragDropEffects.Copy:DragDropEffects.None;e.Handled=true;};drop.Drop+=delegate(object sender,DragEventArgs e){if(e.Data.GetDataPresent(DataFormats.FileDrop))Guard(delegate{ImportAppProfiles((string[])e.Data.GetData(DataFormats.FileDrop));});};appsList=new StackPanel();card.Children.Add(appsList);
  var head=new StackPanel{Margin=new Thickness(0,0,0,12)};scopeChoice=Choice(head,L.T("配置用于"),new string[0]);Get<StackPanel>("TouchPage").Children.Insert(0,head);scopeChoice.SelectionChanged+=delegate{if(scopeLoading)return;var item=scopeChoice.SelectedItem as ScopeChoice;if(item!=null)Guard(delegate{SelectScope(item.Path);});};if(string.IsNullOrEmpty(full.GlobalEditingId))full.GlobalEditingId=full.EditingId;RefreshApps();SyncScope();
 }
 void SyncScope(){if(scopeChoice==null)return;scopeLoading=true;var items=new List<ScopeChoice>{new ScopeChoice{Label=L.T("全局配置 · 没有单独设置时使用")}};items.AddRange(full.Apps.Select(a=>new ScopeChoice{Path=a.Path,Label=a.ToString()}));scopeChoice.ItemsSource=items;scopeChoice.SelectedItem=items.Find(x=>string.Equals(x.Path,editingAppPath,StringComparison.OrdinalIgnoreCase));scopeLoading=false;}
 void SelectScope(string path){if(string.Equals(path,editingAppPath,StringComparison.OrdinalIgnoreCase))return;if(recorder!=null)throw new Exception(L.T("请先结束录制再切换应用。"));ReadEditor();SaveLibrary();editingAppPath=path;var a=EditingApp();full.EditingId=a==null?full.GlobalEditingId:a.PresetId;padBook=Clone(full.Drafts.ContainsKey(full.EditingId)?full.Drafts[full.EditingId]:ActivePreset().Pads);LoadPad();SyncScope();UpdateFullStatus();}
 void ImportAppProfiles(IEnumerable<string> paths){ReadEditor();var errors=new List<string>();int added=0;foreach(string raw in paths)try{string path=ResolvePath(raw);if(Directory.Exists(path))throw new Exception(L.T("请选择实际运行的 EXE。"));if(full.Apps.Any(x=>string.Equals(x.Path,path,StringComparison.OrdinalIgnoreCase)))continue;if(full.Apps.Count>=200)throw new Exception(L.T("最多 200 个应用。"));var preset=AddFull(System.IO.Path.GetFileNameWithoutExtension(path),CommittedPads());full.Apps.Add(new AppAssignment{Path=path,PresetId=preset.Id});added++;}catch(Exception e){errors.Add(System.IO.Path.GetFileName(raw)+"："+e.Message);}SaveLibrary();RefreshApps();SyncScope();Notice(L.T("已导入 ")+added+L.T(" 个应用。点击设置，编辑后应用；名单保持不变。"));if(errors.Count>0)MessageBox.Show(window,string.Join("\n",errors.ToArray()),L.T("部分应用未导入"));}
 void RefreshApps(){if(appsList==null)return;appsList.Children.Clear();if(full.Apps.Count==0){Hint(appsList,L.T("尚未添加应用。当前所有允许接管的应用都使用全局配置。"));return;}foreach(var a in full.Apps){var entry=a;var row=new Grid{Margin=new Thickness(0,7,0,7)};row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(38)});row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});row.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});row.Children.Add(new Image{Source=MakeRule(a.Path,false).AppIcon,Width=26,Height=26});var info=new StackPanel{Margin=new Thickness(0,0,12,0)};row.Children.Add(info);Grid.SetColumn(info,1);info.Children.Add(new TextBlock{Text=a.ToString(),FontWeight=FontWeights.SemiBold});Hint(info,a.Applied==null?L.T("使用全局配置"):L.T("单独配置 · ")+a.AppliedName);var path=new TextBlock{Text=a.Path,FontSize=10,Foreground=Brushes.SlateGray,TextTrimming=TextTrimming.CharacterEllipsis,TextWrapping=TextWrapping.NoWrap,ToolTip=a.Path};info.Children.Add(path);var edit=new Button{Content=L.T("设置"),Padding=new Thickness(14,7,14,7),VerticalAlignment=VerticalAlignment.Center};row.Children.Add(edit);Grid.SetColumn(edit,2);edit.Click+=delegate{Guard(delegate{SelectScope(entry.Path);Navigate("Touch");});};var more=new Button{Content="•••",Margin=new Thickness(6,0,0,0),VerticalAlignment=VerticalAlignment.Center,Padding=new Thickness(12,7,12,7)};row.Children.Add(more);Grid.SetColumn(more,3);more.Click+=delegate{var menu=ActionMenu();MenuAction(menu,L.T("改用全局配置"),delegate{entry.Applied=null;entry.AppliedName=null;SaveLibrary();RestartProfiles();RefreshApps();UpdateFullStatus();});MenuAction(menu,L.T("移除应用"),delegate{if(editingAppPath==entry.Path)SelectScope(null);full.Apps.Remove(entry);SaveLibrary();RestartProfiles();RefreshApps();SyncScope();});menu.PlacementTarget=more;menu.IsOpen=true;};appsList.Children.Add(row);}}
 void RestartProfiles(){if(fullTrial)EndFullTrial();if(liveBridge){Stop();Toggle();}}
 string WriteRuntimeApps(string session){var runtime=new RuntimeProfiles{Apps=full.Apps.Where(a=>a.Applied!=null).Select(Clone).ToList()};runtime.Validate();string path=System.IO.Path.Combine(AppPaths.Logs,session+"-apps.json");AtomicWrite(path,new JavaScriptSerializer{MaxJsonLength=8388608}.Serialize(runtime));return "appProfiles="+path+"\n"+string.Join("",runtime.Apps.Select(a=>"profileTarget="+a.Path+"\n").ToArray());}
 void TestAppProfiles(){var global=CommittedPads();string json=global.Json();var local=Clone(global);local.Bindings=new Dictionary<string,BindingAction>{{"L4",new BindingAction{Kind="keyboard",Chord="Win+D"}}};var runtime=new RuntimeProfiles();runtime.Apps.Add(new AppAssignment{Path=@"C:\Games\one.exe",Applied=local});runtime.Validate();if(runtime.Select(@"c:\games\ONE.exe",global).EffectiveBindings()["L4"].Chord!="Win+D")throw new Exception("App case-insensitive matching");if(runtime.Select(@"C:\Other\one.exe",global).Json()!=json)throw new Exception("App matched basename instead of path");if(CommittedPads().Json()!=json)throw new Exception("App polluted global");runtime.Apps[0].Applied=null;if(runtime.Select(@"C:\Games\one.exe",global).Json()!=json)throw new Exception("Global fallback failed");}
}
