using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
internal sealed partial class PadHop {
 string selectedDevicePath="";ComboBox deviceBox;TextBlock deviceHint;bool deviceLoading;
 sealed class DeviceChoice{public string Path{get;set;} public uint Pid{get;set;} public string Label{get;set;} public bool Online;public override string ToString(){return Label;}}
 void BuildDevices(bool live){values.TryGetValue("devicePath",out selectedDevicePath);selectedDevicePath=selectedDevicePath??"";var parent=Get<StackPanel>("DesktopPage");var card=Card(parent,L.T("生效设备"));var border=parent.Children[parent.Children.Count-1];parent.Children.Remove(border);parent.Children.Insert(0,border);var deviceRow=new Grid();deviceRow.ColumnDefinitions.Add(new ColumnDefinition());deviceRow.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});card.Children.Add(deviceRow);deviceBox=new ComboBox{MinWidth=350,Padding=new Thickness(9),VerticalAlignment=VerticalAlignment.Center};deviceRow.Children.Add(deviceBox);var refresh=new Button{Content=L.T("刷新设备"),Padding=new Thickness(16,10,16,10),Margin=new Thickness(12,0,0,0),VerticalAlignment=VerticalAlignment.Center,HorizontalAlignment=HorizontalAlignment.Right};refresh.Click+=delegate{Guard(RefreshDevices);};Grid.SetColumn(refresh,1);deviceRow.Children.Add(refresh);deviceHint=Hint(card,L.T("仅接管所选 SC2。切换连接方式后，请重新选择；不会自动接管其他设备。"));deviceBox.SelectionChanged+=delegate{if(deviceLoading)return;Stop();var d=deviceBox.SelectedItem as DeviceChoice;selectedDevicePath=d==null?"":d.Path;values["devicePath"]=selectedDevicePath;AtomicWrite(System.IO.Path.Combine(AppPaths.Data,"desktop.ini"),Settings());ShowDeviceStatus();};deviceLoading=true;deviceBox.Items.Add(new DeviceChoice{Path="",Label=L.T("未选择设备 · 不接管")});deviceBox.SelectedIndex=0;deviceLoading=false;if(live)window.Dispatcher.BeginInvoke(new Action(delegate{Guard(RefreshDevices);}));}
 void ShowDeviceStatus(){var d=deviceBox.SelectedItem as DeviceChoice;deviceHint.Text=d==null || string.IsNullOrEmpty(d.Path)?L.T("未选择设备，不会接管任何手柄。"):!d.Online?L.T("所选设备未连接，不会自动切换到其他手柄。"):d.Pid==0x1303?L.T("蓝牙 · 输入与触觉已实测。只接管此设备。"):L.T("USB / 接收器 · 输入兼容性待实测，当前不发送触觉；录制仅支持蓝牙。");}
 void RefreshDevices(){string exe=AppPaths.Engine;string file=System.IO.Path.Combine(AppPaths.Data,"logs","devices.json");Directory.CreateDirectory(System.IO.Path.GetDirectoryName(file));using(var p=Process.Start(new ProcessStartInfo(exe,"--devices-json "+Quote(file)){UseShellExecute=false,CreateNoWindow=true})){if(!p.WaitForExit(4000)){p.Kill();throw new Exception(L.T("设备刷新超时，请重试。"));}if(p.ExitCode!=0)throw new Exception(L.T("无法读取设备列表。"));}var rows=new JavaScriptSerializer().Deserialize<List<DeviceChoice>>(File.ReadAllText(file));deviceLoading=true;try{deviceBox.Items.Clear();var none=new DeviceChoice{Path="",Label=L.T("未选择设备 · 不接管")};deviceBox.Items.Add(none);DeviceChoice chosen=none;foreach(var d in rows){d.Online=true;d.Label=(string.IsNullOrWhiteSpace(d.Label)?"Steam Controller":d.Label)+L.T(" · 蓝牙");deviceBox.Items.Add(d);if(string.Equals(d.Path,selectedDevicePath,StringComparison.OrdinalIgnoreCase))chosen=d;}if(chosen==none && selectedDevicePath.Length>0){chosen=new DeviceChoice{Path=selectedDevicePath,Label=L.T("已选 SC2 · 未连接")};deviceBox.Items.Add(chosen);}deviceBox.SelectedItem=chosen;}finally{deviceLoading=false;}ShowDeviceStatus();}
 void RequireDevice(){RefreshDevices();var d=deviceBox.SelectedItem as DeviceChoice;if(d==null || !d.Online || string.IsNullOrEmpty(d.Path))throw new Exception(L.T("请先在接管状态中选择已连接的 SC2。"));}
 void BuildScope(){var old=Get<CheckBox>("Global");var p=old.Parent as Panel;int index=p.Children.IndexOf(old);old.Visibility=Visibility.Collapsed;var row=new StackPanel{Orientation=Orientation.Horizontal};var black=new RadioButton{Content=L.T("黑名单模式"),GroupName="AppScope",Style=(Style)window.FindResource("ScopeSegment"),Margin=new Thickness(0,0,4,0),IsChecked=old.IsChecked==true};var white=new RadioButton{Content=L.T("白名单模式"),GroupName="AppScope",Style=(Style)window.FindResource("ScopeSegment"),IsChecked=old.IsChecked!=true};row.Children.Add(black);row.Children.Add(white);p.Children.Insert(index,new Border{Child=row,Background=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(17,29,39)),CornerRadius=new CornerRadius(6),Padding=new Thickness(4),HorizontalAlignment=HorizontalAlignment.Left,Margin=new Thickness(0,14,0,8)});black.Checked+=delegate{old.IsChecked=true;if(ready)Guard(SaveRules);};white.Checked+=delegate{old.IsChecked=false;if(ready)Guard(SaveRules);};}
}
