using System;
using System.IO;
using System.Web.Script.Serialization;
public sealed class WaveSpec {
 public string Kind {get;set;} public int OnUs {get;set;} public int OffUs {get;set;} public int Count {get;set;} public int Command {get;set;} public int Gain {get;set;} public int Hz {get;set;} public int Ms {get;set;}
 public string Source {get;set;}
 public WaveSpec(){Kind="pulse";OnUs=400;OffUs=0;Count=1;Command=1;Gain=-12;Hz=160;Ms=10;Source=L.T("默认短脉冲");}
 public byte[] Packet(bool left){if(Kind=="none")return null;if(Kind=="pulse"){if(OnUs<1 || OnUs>5000 || OffUs<0 || OffUs>5000 || Count<1 || Count>100 || (long)(OnUs+OffUs)*Count>80000)throw new Exception(L.T("脉冲需在 80 ms 内，通电 1–5000 μs、间隔 0–5000 μs、重复 1–100 次。"));var p=new byte[]{0x81,(byte)(left?1:0),0,0,0,0,0,0};Array.Copy(BitConverter.GetBytes((ushort)OnUs),0,p,2,2);Array.Copy(BitConverter.GetBytes((ushort)OffUs),0,p,4,2);Array.Copy(BitConverter.GetBytes((ushort)Count),0,p,6,2);return p;}if(Gain<-30 || Gain>0)throw new Exception(L.T("强度范围为 -30 至 0 dB。"));if(Kind=="command"){if(Command!=1 && Command!=2)throw new Exception(L.T("仅支持内置点振和点击。"));return new byte[]{0x82,(byte)(left?0:1),(byte)Command,unchecked((byte)Gain)};}if(Kind!="tone" || Hz<40 || Hz>500 || Ms<1 || Ms>80)throw new Exception(L.T("音调需为 40–500 Hz，1–80 ms。"));return new byte[]{0x83,(byte)(left?0:1),unchecked((byte)Gain),(byte)Hz,(byte)(Hz>>8),(byte)Ms,0,0,0,0};}
 public static WaveSpec FromPacket(byte[] p,string source){if(p==null || p.Length<4)throw new Exception(L.T("报文不完整。"));var w=new WaveSpec{Source=source};int n=p[0]==0x81?8:p[0]==0x82?4:p[0]==0x83?10:0;if(n==0 || p.Length<n)throw new Exception(L.T("此类反馈暂不支持编辑。"));for(int i=n;i<p.Length;i++)if(p[i]!=0)throw new Exception(L.T("存在未知尾部参数。"));if(p[0]==0x81){w.Kind="pulse";w.OnUs=BitConverter.ToUInt16(p,2);w.OffUs=BitConverter.ToUInt16(p,4);w.Count=BitConverter.ToUInt16(p,6);}else if(p[0]==0x82){w.Kind="command";w.Command=p[2];w.Gain=(sbyte)p[3];}else{if(BitConverter.ToUInt16(p,7)!=0 || p[9]!=0)throw new Exception(L.T("暂不支持带调制的音调。"));w.Kind="tone";w.Gain=(sbyte)p[2];w.Hz=BitConverter.ToUInt16(p,3);w.Ms=BitConverter.ToUInt16(p,5);}w.Packet(false);return w;}
 public override string ToString(){return Kind=="none"?L.T("关闭"):Kind=="pulse"?OnUs+" μs / "+OffUs+" μs / "+Count+L.T(" 次"):Kind=="command"?L.T("内置 ")+Command+" / "+Gain+" dB":Hz+" Hz / "+Ms+" ms / "+Gain+" dB";}
}
public sealed class PadProfile {
 public BindingAction PressAction {get;set;} public System.Collections.Generic.Dictionary<string,BindingAction> Directions {get;set;} public int Deadzone {get;set;}

 public int TouchGraceMs {get;set;} public int ReleaseGraceMs {get;set;} public int MotionPressureLimit {get;set;}
 public bool SteamlessHaptics {get;set;} public WaveSpec ReleaseWave {get;set;}
 public bool ReverseScroll {get;set;} public double ScrollReversalPercent {get;set;}
 public double DragThresholdPx {get;set;}
 public bool FineScroll {get;set;} public double DragScale {get;set;}
 public string PresetId {get;set;}
 public string Action {get;set;} public string Click {get;set;} public double Speed {get;set;} public double Smooth {get;set;} public double Friction {get;set;} public double ScrollUnits {get;set;} public bool Inertia {get;set;}
 public int Press {get;set;} public int Release {get;set;} public int StableMs {get;set;} public int Interval {get;set;} public int Spacing {get;set;} public WaveSpec Motion {get;set;} public WaveSpec PressWave {get;set;}
 public PadProfile(){DragThresholdPx=6;ScrollReversalPercent=.4;Deadzone=25;PressAction=new BindingAction();Directions=new System.Collections.Generic.Dictionary<string,BindingAction>();foreach(string d in new[]{"UP","DOWN","LEFT","RIGHT"})Directions[d]=new BindingAction{Kind="keyboard",Chord=d.Substring(0,1)+d.Substring(1).ToLowerInvariant()};TouchGraceMs=48;ReleaseGraceMs=180;MotionPressureLimit=900;ReleaseWave=new WaveSpec{Kind="none",Source=L.T("默认关闭松开反馈")};DragScale=.65;Action="mouse";Click="left";Speed=.02;Smooth=12;Friction=8;ScrollUnits=2000;Inertia=true;Press=3500;Release=2200;StableMs=60;Interval=40;Spacing=12;Motion=new WaveSpec();PressWave=new WaveSpec{Kind="command",Source=L.T("默认点击")};}
 public void Validate(){if(double.IsNaN(DragThresholdPx) || DragThresholdPx<0 || DragThresholdPx>30)throw new Exception(L.T("拖拽起步距离必须在 0–30 之间。"));if(double.IsNaN(ScrollReversalPercent) || ScrollReversalPercent<0 || ScrollReversalPercent>3)throw new Exception(L.T("换向缓冲必须在 0–3% 之间。"));if(Deadzone<5 || Deadzone>80 || PressAction==null || Directions==null || Directions.Count!=4)throw new Exception(L.T("触摸板映射配置无效。"));PressAction.Validate();foreach(string d in new[]{"UP","DOWN","LEFT","RIGHT"}){if(!Directions.ContainsKey(d)||Directions[d]==null)throw new Exception(L.T("方向映射缺失。"));Directions[d].Validate();}if(TouchGraceMs<0 || TouchGraceMs>500 || ReleaseGraceMs<0 || ReleaseGraceMs>500 || MotionPressureLimit<0 || MotionPressureLimit>10000)throw new Exception(L.T("防误触参数超出范围。"));if(Action!="mouse" && Action!="scroll" && Action!="directions" && Action!="leftStick" && Action!="rightStick" && Action!="none")throw new Exception(L.T("未知触摸板动作。"));if(Click!="left" && Click!="right" && Click!="binding" && Click!="none")throw new Exception(L.T("未知点击动作。"));if(DragScale<.1 || DragScale>1 || double.IsNaN(DragScale))throw new Exception(L.T("拖动速度超出范围。"));if(double.IsNaN(Speed+Smooth+Friction+ScrollUnits) || double.IsInfinity(Speed+Smooth+Friction+ScrollUnits) || Speed<.001 || Speed>.1 || Smooth<0 || Smooth>100 || Friction<1 || Friction>30 || ScrollUnits<200 || ScrollUnits>20000 || Press<500 || Press>32767 || Release<0 || Release>=Press || StableMs<0 || StableMs>150 || Interval<30 || Interval>200 || Spacing<1 || Spacing>500)throw new Exception(L.T("触摸板参数超出范围，松开阈值应小于按下阈值。"));if(Motion==null || PressWave==null)throw new Exception(L.T("触觉配置缺失。"));Motion.Packet(false);PressWave.Packet(false);if(ReleaseWave==null)throw new Exception(L.T("缺少松开反馈。"));ReleaseWave.Packet(false);}
}
public sealed partial class PadBook {
 public System.Collections.Generic.Dictionary<string,BindingAction> Bindings {get;set;}
 public System.Collections.Generic.Dictionary<string,BindingAction> EffectiveBindings(){EnsureInputLayout();var b=Bindings==null?new System.Collections.Generic.Dictionary<string,BindingAction>():new System.Collections.Generic.Dictionary<string,BindingAction>(Bindings);if(Bindings==null && KeyboardButton!="none")b[KeyboardButton]=new BindingAction{Kind="osk"};for(int i=0;i<2;i++){var p=i==0?Left:Right;string prefix=i==0?"LP":"RP";if(p.Click=="binding")b[(i==0?"LPRESS":"RPRESS")]=p.PressAction;if(p.Action=="directions")foreach(var d in p.Directions)b[prefix+"_"+d.Key]=d.Value;}for(int i=0;i<2;i++)foreach(var d in (i==0?LeftStick:RightStick).Bindings())b[(i==0?"LS_":"RS_")+d.Key]=d.Value;return b;}

 public bool LeftStickWasd {get;set;}
 public bool GamepadEnabled {get;set;}
 public string KeyboardButton {get;set;}
 public int Version {get;set;} public PadProfile Left {get;set;} public PadProfile Right {get;set;}
 public PadBook(){KeyboardButton="L5";Version=1;Left=new PadProfile{Action="scroll",Click="right"};Right=new PadProfile();}
 public void Validate(){EnsureInputLayout();if(LeftStick==null || RightStick==null)throw new Exception(L.T("摇杆配置缺失。"));LeftStick.Validate();RightStick.Validate();if(Bindings!=null){if(Bindings.Count>InputCatalog.Buttons.Length)throw new Exception(L.T("按键绑定过多。"));foreach(var b in Bindings){if(InputCatalog.Mask(b.Key)==0 || b.Value==null)throw new Exception(L.T("未知手柄按键。"));b.Value.Validate();}}if(KeyboardButton!="none" && KeyboardButton!="L4" && KeyboardButton!="L5" && KeyboardButton!="R4" && KeyboardButton!="R5")throw new Exception(L.T("未知键盘绑定。"));if(Version!=1 || Left==null || Right==null)throw new Exception(L.T("不支持的配置版本。"));Left.Validate();Right.Validate();}
 public static PadBook Load(string path){if(new FileInfo(path).Length>1048576)throw new Exception(L.T("配置文件过大。"));var b=new JavaScriptSerializer().Deserialize<PadBook>(File.ReadAllText(path));if(b==null)throw new Exception(L.T("配置为空。"));b.Validate();return b;}
 public string Json(){Validate();return new JavaScriptSerializer().Serialize(this);}
 public static void Test(){var b=new PadBook();b.Validate();if(b.Left.PressWave.Packet(true)[1]!=0 || b.Right.PressWave.Packet(false)[1]!=1 || b.Left.Motion.Packet(true)[1]!=1 || b.Right.Motion.Packet(false)[1]!=0)throw new Exception("Report-specific side routing");b.Left.Motion.OnUs=700;var copy=new JavaScriptSerializer().Deserialize<PadBook>(b.Json());if(copy.Right.Motion.OnUs!=400 || copy.Left.Motion.OnUs!=700 || copy.Left.Click!="right")throw new Exception("Independent pad profile roundtrip");bool bad=false;try{new WaveSpec{OnUs=5000,Count=100}.Packet(false);}catch{bad=true;}if(!bad)throw new Exception("Unbounded waveform");}
}
