using System;
using System.Collections.Generic;
internal sealed partial class PadHop {
 static PadBook StarterPreset(string mode){var b=SteamlessPreset(new PadBook());b.KeyboardButton="none";b.Bindings=new Dictionary<string,BindingAction>();if(mode=="gamepad"){b.GamepadEnabled=true;foreach(var p in new[]{b.Left,b.Right}){p.Action="none";p.Click="none";p.Motion=new WaveSpec{Kind="none"};p.PressWave=new WaveSpec{Kind="none"};p.ReleaseWave=new WaveSpec{Kind="none"};}}else if(mode=="mouse"){b.Left.Action="scroll";b.Left.Click="right";b.Right.Action="mouse";b.Right.Click="left";b.Bindings["L5"]=new BindingAction{Kind="osk"};}else{b.LeftStickWasd=true;b.Left.Action="directions";b.Left.Click="none";b.Right.Action="mouse";b.Right.Click="left";string[] dirs={"UP","DOWN","LEFT","RIGHT"},keys={"W","S","A","D"};for(int i=0;i<4;i++)b.Left.Directions[dirs[i]]=new BindingAction{Kind="keyboard",Chord=keys[i]};var map=new Dictionary<string,string>{{"A","Space"},{"B","Escape"},{"X","R"},{"Y","E"},{"LB","Tab"},{"RB","Shift"},{"L3","Shift"},{"R3","Ctrl"},{"VIEW","Tab"},{"MENU","Escape"},{"UP","1"},{"DOWN","2"},{"LEFT","3"},{"RIGHT","4"}};foreach(var pair in map)b.Bindings[pair.Key]=new BindingAction{Kind="keyboard",Chord=pair.Value};b.Bindings["LT"]=new BindingAction{Kind="mouse",Chord="right"};b.Bindings["RT"]=new BindingAction{Kind="mouse",Chord="left"};b.Bindings["L5"]=new BindingAction{Kind="osk"};}b.InputLayoutVersion=0;b.Validate();return b;}
 void EnsureStarterPresets(){
  // Old versions did not persist origin. Keep every old entry as personal;
  // names cannot prove provenance, especially after edits, renames or imports.
  string[] modes={"gamepad","mouse","keyboard"};string[] names={L.T("手柄模式"),L.T("鼠标模式"),L.T("键盘模式 · WASD 与鼠标")};
  for(int i=0;i<modes.Length;i++)if(!full.Presets.Exists(p=>p.BuiltInMode==modes[i]) && full.Presets.Count<200)full.Presets.Add(new FullPreset{Id=Guid.NewGuid().ToString("N"),Name=names[i],BuiltInMode=modes[i],Pads=StarterPreset(modes[i])});
  full.StarterPresetsAdded=true;
 }
 static void TestStarterPresets(){var a=StarterPreset("gamepad");if(!a.GamepadEnabled || a.EffectiveBindings().Count!=InputCatalog.Gamepad.Length || a.Left.Action!="none" || a.Right.Click!="none")throw new Exception("Gamepad preset must leave extras unbound");var b=StarterPreset("mouse");if(b.GamepadEnabled || b.Left.Click!="right" || b.Right.Click!="left" || !b.Left.SteamlessHaptics || !b.Right.SteamlessHaptics || !b.Left.FineScroll || b.Left.ScrollUnits!=6000 || b.Right.Speed!=.01125)throw new Exception("Mouse preset");var c=StarterPreset("keyboard");if(!c.LeftStickWasd || c.EffectiveBindings()["LS_UP"].Chord!="W" || c.Bindings["A"].Chord!="Space")throw new Exception("Keyboard preset");if(KeyboardRecorder.Chord(new[]{68,0x5B})!="Win+D")throw new Exception("Recorded Win chord order");}
}
