using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
internal sealed partial class PadHop {
 PadBook padBook=new PadBook();bool editorLoading;int editedSide;TabControl padTabs;ComboBox actionBox,clickBox,eventBox,kindBox,sourceBox,candidateBox;TextBlock padHeading,waveSummary,recordStatus;readonly TextBox[] waveFields=new TextBox[3];readonly TextBlock[] waveLabels=new TextBlock[3];readonly Dictionary<string,TextBox> padFields=new Dictionary<string,TextBox>();ComboBox cadenceMode;Expander cadenceFilters;CheckBox fineScrollBox;ComboBox scrollDirection;StackPanel scrollDirectionHost;CheckBox inertiaBox;Button recordButton,stopRecord;string recordResult;Process recorder;string loadedSource="left";
 string PadPath {get{return System.IO.Path.Combine(AppPaths.Data,"profiles","pads.json");}}
 PadProfile CurrentPad {get{return editedSide==0?padBook.Left:padBook.Right;}}
 WaveSpec CurrentWave {get{return eventBox.SelectedIndex==0?CurrentPad.Motion:eventBox.SelectedIndex==1?CurrentPad.PressWave:CurrentPad.ReleaseWave;}}
 StackPanel Card(Panel parent,string title){var body=new StackPanel();var b=new Border{Style=window.FindResource("Card") as Style,Child=body};body.Children.Add(new TextBlock{Text=title,FontSize=18,FontWeight=FontWeights.SemiBold,Margin=new Thickness(0,0,0,14)});parent.Children.Add(b);return body;}
 TextBlock Hint(Panel p,string text){var t=new TextBlock{Text=text,Foreground=new SolidColorBrush(Color.FromRgb(145,163,181)),FontSize=12,Margin=new Thickness(0,8,0,8)};p.Children.Add(t);Explain(t,text);return t;}
 Button Btn(Panel p,string text,Action action){var b=new Button{Content=text,Style=window.FindResource(typeof(Button)) as Style,Margin=new Thickness(0,5,10,5)};b.Click+=delegate{Guard(action);};p.Children.Add(b);return b;}
 ComboBox Choice(Panel p,string label,string[] choices){Hint(p,label);var c=new ComboBox{ItemsSource=choices,SelectedIndex=0,Margin=new Thickness(0,0,14,6),MinWidth=200,Padding=new Thickness(9),Background=new SolidColorBrush(Color.FromRgb(36,54,70)),Foreground=Brushes.White};p.Children.Add(c);return c;}
 static readonly string[] PadActions={"mouse","scroll","directions","leftStick","rightStick","none"};
 Button padPressButton;StackPanel directionPanel,deadzonePanel;TextBox deadzoneField;readonly Dictionary<string,Button> directionButtons=new Dictionary<string,Button>();
 void SyncPadMappings(){if(padPressButton==null)return;padPressButton.Content=GetBinding(editedSide==0?"LPRESS":"RPRESS").ToString();foreach(var row in directionButtons)row.Value.Content=InputCatalog.ButtonLabel(row.Key)+" · "+CurrentPad.Directions[row.Key];directionPanel.Visibility=CurrentPad.Action=="directions"?Visibility.Visible:Visibility.Collapsed;deadzonePanel.Visibility=CurrentPad.Action=="directions" || CurrentPad.Action=="leftStick" || CurrentPad.Action=="rightStick"?Visibility.Visible:Visibility.Collapsed;}
 Grid waveGrid;Grid cadenceGrid;
 Grid motionGrid;Expander motionExpander;
 readonly Dictionary<string,FrameworkElement> parameterCells=new Dictionary<string,FrameworkElement>();
 readonly Dictionary<TextBox,Slider> numberSliders=new Dictionary<TextBox,Slider>();
 TextBox SliderNumber(Panel parent,double min,double max,double step){var panel=new StackPanel{Margin=new Thickness(0,0,14,8)};parent.Children.Add(panel);var text=new TextBox{Padding=new Thickness(9),Background=new SolidColorBrush(Color.FromRgb(17,29,40)),Foreground=Brushes.White,BorderBrush=new SolidColorBrush(Color.FromRgb(54,79,99))};var slider=new Slider{Minimum=min,Maximum=max,TickFrequency=step,SmallChange=step,LargeChange=step*10,IsSnapToTickEnabled=true,Margin=new Thickness(0,8,0,4)};panel.Children.Add(slider);panel.Children.Add(text);numberSliders[text]=slider;bool sync=false;slider.ValueChanged+=delegate{if(sync)return;sync=true;text.Text=slider.Value.ToString("0.###",CultureInfo.InvariantCulture);sync=false;};text.TextChanged+=delegate{if(sync)return;double n;if(double.TryParse(text.Text,NumberStyles.Float,CultureInfo.InvariantCulture,out n) && !double.IsNaN(n) && !double.IsInfinity(n) && n>=slider.Minimum && n<=slider.Maximum){sync=true;slider.Value=n;sync=false;}};return text;}
 TextBox Number(Panel p,string key,string label){var cell=new StackPanel();p.Children.Add(cell);p=cell;parameterCells[key]=cell;Hint(p,label);double lo=0,hi=100,step=1;switch(key){case "dragThreshold":hi=30;break;case "speed":lo=.05;hi=5;step=.05;break;case "reversal":lo=0;hi=3;step=.1;break;case "scroll":lo=200;hi=20000;step=100;break;case "press":lo=500;hi=32767;step=1;break;case "release":hi=32766;break;case "friction":lo=1;hi=30;step=.1;break;case "interval":lo=30;hi=200;break;case "spacing":lo=1;hi=500;break;case "touchGrace":hi=500;break;case "releaseGrace":hi=500;break;case "motionPressure":hi=10000;step=10;break;}var t=SliderNumber(p,lo,hi,step);padFields[key]=t;return t;}
 Grid Columns(Panel p,int n){var g=new Grid();for(int i=0;i<n;i++)g.ColumnDefinitions.Add(new ColumnDefinition());p.Children.Add(g);return g;}
 StackPanel Column(Grid grid,int col){var s=new StackPanel();Grid.SetColumn(s,col);grid.Children.Add(s);return s;}
 void BuildWorkspace(){if(File.Exists(PadPath))padBook=PadBook.Load(PadPath);else{padBook.Right.Speed=ReadNumber("speed",.02);padBook.Right.Smooth=ReadNumber("smoothMs",12);padBook.Right.Friction=ReadNumber("friction",8);padBook.Left.ScrollUnits=ReadNumber("scrollUnits",2000);}var page=Get<StackPanel>("TouchPage");page.Children.Clear();padTabs=new TabControl{Margin=new Thickness(0,0,0,18),Height=46};padTabs.Items.Add(new TabItem{Header=L.T("左触摸板")});padTabs.Items.Add(new TabItem{Header=L.T("右触摸板")});page.Children.Add(padTabs);padTabs.SelectedIndex=0;
  var movement=Card(page,L.T("触摸板动作"));padHeading=Hint(movement,"");padHeading.Visibility=Visibility.Collapsed;var grid=Columns(movement,2);actionBox=Choice(Column(grid,0),L.T("滑动动作"),new[]{L.T("移动鼠标"),L.T("滚动内容"),L.T("四方向按键"),L.T("模拟左摇杆"),L.T("模拟右摇杆"),L.T("不映射")});var pressHost=Column(grid,1);Hint(pressHost,L.T("按压动作"));padPressButton=Btn(pressHost,"",delegate{EditBinding(editedSide==0?"LPRESS":"RPRESS");});clickBox=new ComboBox{ItemsSource=new[]{"left","right","none","binding"},SelectedIndex=0};directionPanel=new StackPanel();movement.Children.Add(directionPanel);var directions=Columns(directionPanel,2);var dc0=Column(directions,0);var dc1=Column(directions,1);int di=0;foreach(string key in new[]{"UP","DOWN","LEFT","RIGHT"}){string dir=key;directionButtons[dir]=Btn(di++%2==0?dc0:dc1,dir,delegate{EditBinding((editedSide==0?"LP_":"RP_")+dir);});}deadzonePanel=new StackPanel();movement.Children.Add(deadzonePanel);Hint(deadzonePanel,L.T("中心死区 % · 中心范围内不输出方向，越大越不易误触（5–80）"));deadzoneField=SliderNumber(deadzonePanel,5,80,1);var advanced=new StackPanel();motionExpander=new Expander{Header=L.T("移动与按压参数"),Content=advanced,Foreground=Brushes.LightGray,Margin=new Thickness(0,12,0,0)};movement.Children.Add(motionExpander);motionGrid=new Grid();advanced.Children.Add(motionGrid);Number(motionGrid,"speed",L.T("移动速度 ×（0.05–5）"));Number(motionGrid,"smooth",L.T("平滑 ms（0–100）"));Number(motionGrid,"dragThreshold",L.T("拖拽起步距离（0–30）"));Number(motionGrid,"scroll",L.T("滚轮距离（200–20000，越小越快）"));Number(motionGrid,"reversal",L.T("换向缓冲 %（0–3）"));Number(motionGrid,"press",L.T("按下力度（500–32767）"));Number(motionGrid,"release",L.T("松开力度（低于按下力度）"));Number(motionGrid,"friction",L.T("惯性摩擦（1–30）"));inertiaBox=new CheckBox{Content=L.T("轨迹球惯性（移动鼠标时）  ?"),ToolTip=L.T("开启后，手指离开触摸板时鼠标会继续滑行并逐渐减速；再次触摸会停止滑行。关闭后松手即停止。")};advanced.Children.Add(inertiaBox);
  var haptic=Card(page,L.T("触觉反馈"));cadenceMode=Choice(haptic,L.T("触觉触发规则"),new[]{L.T("Steamless · 防误触"),L.T("原有触发规则")});var filters=new StackPanel();cadenceFilters=new Expander{Header=L.T("防误触微调"),Content=filters,Foreground=Brushes.LightGray,Margin=new Thickness(0,8,0,14)};haptic.Children.Add(cadenceFilters);var filterGrid=Columns(filters,3);Number(Column(filterGrid,0),"touchGrace",L.T("触摸缓冲 ms（0–500）"));Number(Column(filterGrid,1),"releaseGrace",L.T("松开缓冲 ms（0–500）"));Number(Column(filterGrid,2),"motionPressure",L.T("按压避让阈值（0–10000）"));Hint(filters,L.T("触摸缓冲：刚碰到板时延后滑动反馈。松开缓冲：点击松开后暂缓滑动反馈。按压避让阈值：压力超过此值时暂停滑动反馈，越低越容易避开按压动作。"));cadenceMode.SelectionChanged+=delegate{if(editorLoading)return;CurrentPad.SteamlessHaptics=cadenceMode.SelectedIndex==0;cadenceFilters.Visibility=CurrentPad.SteamlessHaptics?Visibility.Visible:Visibility.Collapsed;};grid=Columns(haptic,2);eventBox=Choice(Column(grid,0),L.T("编辑哪个事件"),new[]{L.T("滑动反馈"),L.T("按压反馈"),L.T("松开反馈")});kindBox=Choice(Column(grid,1),L.T("反馈方式"),new[]{L.T("短脉冲"),L.T("内置反馈"),L.T("短音调"),L.T("关闭")});grid=Columns(haptic,3);waveGrid=grid;for(int i=0;i<3;i++){var col=Column(grid,i);waveLabels[i]=Hint(col,"");waveFields[i]=SliderNumber(col,0,5000,1);}grid=Columns(haptic,2);cadenceGrid=grid;Number(Column(grid,0),"interval",L.T("滑动最短间隔 ms（30–200）"));Number(Column(grid,1),"spacing",L.T("滑动触发距离 px（1–500）"));waveSummary=Hint(haptic,"");StackPanel row;
  var capture=new StackPanel{Margin=new Thickness(0,10,0,12)};var recordExpander=new Expander{Header=L.T("从 Steam 录入参数 / 打开已有录制"),Content=capture,Foreground=Brushes.LightGray,Margin=new Thickness(0,0,0,18)};haptic.Children.Insert(1,recordExpander);BuildCaptureSetup(capture);sourceBox=Choice(capture,L.T("录制来源（可与当前编辑的目标板不同）"),new[]{L.T("Steam 左触摸板"),L.T("Steam 右触摸板")});row=new StackPanel{Orientation=Orientation.Horizontal};capture.Children.Add(row);recordButton=Btn(row,L.T("开始录制 · 60 秒"),delegate{RecordPad();});stopRecord=Btn(row,L.T("停止录制"),delegate{if(recordResult!=null)File.WriteAllText(recordResult+".stop","stop");});stopRecord.IsEnabled=false;Btn(row,L.T("打开已有录制"),OpenCaptureResult);recordStatus=Hint(capture,L.T("按阶段滑动或按压来源板。录制前保留该板的 Steam 绑定与反馈；录制会暂停 Talaria 接管。"));candidateBox=new ComboBox();Hint(capture,L.T("录制需要管理员确认，临时完整蓝牙日志可能包含其他设备数据，仅保存在本机，结束后恢复日志设置。"));
  BuildPresetLibrary(haptic,recordExpander,capture);var files=Card(page,L.T("保存与复用"));row=new StackPanel{Orientation=Orientation.Horizontal};files.Children.Add(row);Btn(row,L.T("保存左右板配置"),delegate{ReadEditor();SavePads();Notice(L.T("左右板配置已保存，下次打开自动载入。"));});Btn(row,L.T("导出配置"),delegate{ReadEditor();var d=new Microsoft.Win32.SaveFileDialog{Filter=L.T("左右板配置|*.json"),FileName=L.T("SC2-左右触摸板.json")};if(d.ShowDialog(window)==true)AtomicWrite(d.FileName,padBook.Json());});Btn(row,L.T("导入配置"),ImportPadBook);Btn(row,L.T("复制到另一块板"),delegate{ReadEditor();var clone=new JavaScriptSerializer().Deserialize<PadProfile>(new JavaScriptSerializer().Serialize(CurrentPad));if(editedSide==0)padBook.Right=clone;else padBook.Left=clone;SavePads();Notice(L.T("已复制到另一板；左右仍可分别微调。"));});
  CompactFiles(page,files);
  padTabs.SelectionChanged+=delegate(object sender,SelectionChangedEventArgs e){if(e.Source!=padTabs || editorLoading)return;int next=padTabs.SelectedIndex;try{ReadEditor();editedSide=next;LoadPad();}catch(Exception ex){editorLoading=true;padTabs.SelectedIndex=editedSide;editorLoading=false;Notice(ex.Message);}};
  int previousEvent=0;eventBox.SelectionChanged+=delegate{if(editorLoading)return;int next=eventBox.SelectedIndex;try{ReadWave(previousEvent);previousEvent=next;LoadWave();}catch(Exception ex){editorLoading=true;eventBox.SelectedIndex=previousEvent;editorLoading=false;Notice(ex.Message);}};
  kindBox.SelectionChanged+=delegate{if(editorLoading)return;var w=CurrentWave;w.Kind=new[]{"pulse","command","tone","none"}[kindBox.SelectedIndex];LoadWave();};fineScrollBox=new CheckBox{Content=L.T("细腻滚动 · 小幅滑动也输出滚动量"),Foreground=Brushes.LightGray};advanced.Children.Add(fineScrollBox);scrollDirectionHost=new StackPanel();advanced.Children.Add(scrollDirectionHost);scrollDirection=Choice(scrollDirectionHost,L.T("滚动方向"),new[]{L.T("滚轮方向 · 上滑向上滚"),L.T("自然方向 · 上滑向下滚")});fineScrollBox.ToolTip=L.T("参考 SteamlessController：滚动量无需攒满一格才发出。实际平滑程度取决于应用是否支持细粒度滚轮；关闭可保留原来逐格滚动。");actionBox.SelectionChanged+=delegate{if(!editorLoading && actionBox.SelectedIndex>=0){CurrentPad.Action=PadActions[actionBox.SelectedIndex];SyncButtons();}fineScrollBox.Visibility=actionBox.SelectedIndex==1?Visibility.Visible:Visibility.Collapsed;UpdateMotionFields();};inertiaBox.Checked+=delegate{UpdateMotionFields();};inertiaBox.Unchecked+=delegate{UpdateMotionFields();};LoadPad();
  string recent=System.IO.Path.Combine(AppPaths.Data,"profiles","last-capture.txt");if(File.Exists(recent))try{string f=File.ReadAllText(recent).Trim();if(File.Exists(f))LoadCandidates(f);}catch(Exception e){recordStatus.Text=L.T("上次录制未载入：")+e.Message;}
 }
 void LoadPad(){SyncButtons();editorLoading=true;try{var p=CurrentPad;cadenceMode.SelectedIndex=p.SteamlessHaptics?0:1;cadenceFilters.Visibility=p.SteamlessHaptics?Visibility.Visible:Visibility.Collapsed;Set("touchGrace",p.TouchGraceMs);Set("releaseGrace",p.ReleaseGraceMs);Set("motionPressure",p.MotionPressureLimit);if(fineScrollBox!=null)fineScrollBox.IsChecked=p.FineScroll;actionBox.SelectedIndex=Array.IndexOf(PadActions,p.Action);deadzoneField.Text=p.Deadzone.ToString();clickBox.SelectedIndex=p.Click=="left"?0:p.Click=="right"?1:p.Click=="binding"?3:2;Set("speed",p.Speed/.02);Set("smooth",p.Smooth);Set("dragThreshold",p.DragThresholdPx);Set("scroll",p.ScrollUnits);Set("reversal",p.ScrollReversalPercent);scrollDirection.SelectedIndex=p.ReverseScroll?1:0;Set("press",p.Press);Set("release",p.Release);Set("friction",p.Friction);Set("interval",p.Interval);Set("spacing",p.Spacing);inertiaBox.IsChecked=p.Inertia;padHeading.Text=L.T("当前目标：")+(editedSide==0?L.T("左触摸板"):L.T("右触摸板"))+L.T(" · 保存后独立生效");}finally{editorLoading=false;}LoadWave();SyncPresetChoice();if(fineScrollBox!=null)fineScrollBox.Visibility=actionBox.SelectedIndex==1?Visibility.Visible:Visibility.Collapsed;UpdateMotionFields();}
 void Set(string k,double v){padFields[k].Text=v.ToString("0.######",CultureInfo.InvariantCulture);}double N(string k){return double.Parse(padFields[k].Text,CultureInfo.InvariantCulture);}
 void ReadEditor(){if(padTabs==null)return;ReadSticks();ReadWave(eventBox.SelectedIndex);var p=CurrentPad;p.Action=PadActions[actionBox.SelectedIndex];p.Deadzone=int.Parse(deadzoneField.Text);p.Click=new[]{"left","right","none","binding"}[clickBox.SelectedIndex];p.Speed=N("speed")*.02;p.Smooth=N("smooth");p.DragThresholdPx=N("dragThreshold");p.ScrollUnits=N("scroll");p.ScrollReversalPercent=N("reversal");p.ReverseScroll=scrollDirection.SelectedIndex==1;p.Press=checked((int)N("press"));p.Release=checked((int)N("release"));p.Friction=N("friction");p.Interval=checked((int)N("interval"));p.Spacing=checked((int)N("spacing"));p.TouchGraceMs=checked((int)N("touchGrace"));p.ReleaseGraceMs=checked((int)N("releaseGrace"));p.MotionPressureLimit=checked((int)N("motionPressure"));p.Inertia=inertiaBox.IsChecked==true;if(fineScrollBox!=null)p.FineScroll=fineScrollBox.IsChecked==true;p.Validate();}
 void ReadWave(int role){var w=role==0?CurrentPad.Motion:role==1?CurrentPad.PressWave:CurrentPad.ReleaseWave;if(w.Kind=="none")return;int a=int.Parse(waveFields[0].Text),b=int.Parse(waveFields[1].Text),c=w.Kind=="command"?0:int.Parse(waveFields[2].Text);if(w.Kind=="pulse"){w.OnUs=a;w.OffUs=b;w.Count=c;}else if(w.Kind=="command"){w.Command=a;w.Gain=b;}else{w.Hz=a;w.Ms=b;w.Gain=c;}w.Packet(editedSide==0);}
 void LoadWave(){editorLoading=true;try{var w=CurrentWave;kindBox.SelectedIndex=w.Kind=="pulse"?0:w.Kind=="command"?1:w.Kind=="tone"?2:3;string[] labels=w.Kind=="pulse"?new[]{L.T("通电时长 μs（1–5000）"),L.T("关闭间隔 μs（0–5000）"),L.T("重复次数（1–100）")}:w.Kind=="command"?new[]{L.T("类型（1 点振 / 2 强点击）"),L.T("强度 dB（-30 至 0）"),""}:new[]{L.T("频率 Hz（40–500）"),L.T("时长 ms（1–80）"),L.T("强度 dB（-30 至 0）")};int[] vals=w.Kind=="pulse"?new[]{w.OnUs,w.OffUs,w.Count}:w.Kind=="command"?new[]{w.Command,w.Gain,0}:new[]{w.Hz,w.Ms,w.Gain};for(int i=0;i<3;i++){waveLabels[i].Text=labels[i];Explain(waveLabels[i],labels[i]);var slider=numberSliders[waveFields[i]];double[] lo=w.Kind=="pulse"?new double[]{1,0,1}:w.Kind=="command"?new double[]{1,-30,0}:new double[]{40,1,-30};double[] hi=w.Kind=="pulse"?new double[]{5000,5000,100}:w.Kind=="command"?new double[]{2,0,1}:new double[]{500,80,0};slider.Minimum=Math.Min(slider.Minimum,lo[i]);slider.Maximum=hi[i];slider.Minimum=lo[i];waveFields[i].Text=vals[i].ToString();waveFields[i].IsEnabled=w.Kind!="none" && !(w.Kind=="command" && i==2);slider.IsEnabled=waveFields[i].IsEnabled;}waveGrid.ColumnDefinitions.Clear();int count=w.Kind=="none"?0:w.Kind=="command"?2:3;for(int i=0;i<count;i++)waveGrid.ColumnDefinitions.Add(new ColumnDefinition());for(int i=0;i<3;i++)((FrameworkElement)waveLabels[i].Parent).Visibility=i<count?Visibility.Visible:Visibility.Collapsed;waveGrid.Visibility=count==0?Visibility.Collapsed:Visibility.Visible;cadenceGrid.Visibility=eventBox.SelectedIndex==0 && w.Kind!="none"?Visibility.Visible:Visibility.Collapsed;waveSummary.Text=L.T("当前：")+w+L.T("\n来源：")+w.Source+" → "+(editedSide==0?L.T("左板"):L.T("右板"))+" / "+(eventBox.SelectedIndex==0?L.T("滑动"):eventBox.SelectedIndex==1?L.T("按压"):L.T("松开"));}finally{editorLoading=false;}}
 void SavePads(){if(testing)return;Directory.CreateDirectory(System.IO.Path.GetDirectoryName(PadPath));AtomicWrite(PadPath,padBook.Json());SaveLibrary();}
 void ImportPadBook(){var d=new Microsoft.Win32.OpenFileDialog{Filter=L.T("触摸板配置|*.json")};if(d.ShowDialog(window)!=true)return;var b=PadBook.Load(d.FileName);padBook=b;LoadPad();SavePads();Notice(L.T("左右板配置已导入。"));}
 sealed class Candidate {public WaveSpec Wave;public string Text;public string Phase;public int Count;public override string ToString(){return Text;}}
 void OpenCaptureResult(){var d=new Microsoft.Win32.OpenFileDialog{Filter=L.T("录制结果|haptics.json")};if(d.ShowDialog(window)==true){LoadCandidates(d.FileName);CreateRecordedPreset();}}
 void LoadCandidates(string file){file=CleanRecording(file);if(new FileInfo(file).Length>16*1024*1024)throw new Exception(L.T("录制结果过大。"));var d=new JavaScriptSerializer{MaxJsonLength=16*1024*1024}.DeserializeObject(File.ReadAllText(file)) as Dictionary<string,object>;if(d==null || !d.ContainsKey("candidates"))throw new Exception(L.T("不是录制结果。"));loadedSource=d.ContainsKey("capture_side")?Convert.ToString(d["capture_side"]):"left";candidateBox.Items.Clear();int skipped=0;foreach(var obj in (object[])d["candidates"]){var c=(Dictionary<string,object>)obj;string phase=Convert.ToString(c["phase"]);if(phase!="slow_slide" && phase!="fast_slide" && phase!="press" && phase!="release")continue;try{byte id=Convert.ToByte(Convert.ToString(c["report_id"]).Substring(2),16);string hex=Convert.ToString(c["payload_hex"]);byte[] p=new byte[1+hex.Length/2];p[0]=id;for(int i=1;i<p.Length;i++)p[i]=Convert.ToByte(hex.Substring((i-1)*2,2),16);byte expected=(byte)(id==0x81?(loadedSource=="left"?1:0):(loadedSource=="left"?0:1));if(p[1]!=expected)continue;var wave=WaveSpec.FromPacket(p,(loadedSource=="left"?L.T("Steam 左板"):L.T("Steam 右板"))+" · "+System.IO.Path.GetFileName(System.IO.Path.GetDirectoryName(file)));candidateBox.Items.Add(new Candidate{Wave=wave,Phase=phase,Count=Convert.ToInt32(c["count"]),Text=(phase=="slow_slide"?L.T("慢滑"):phase=="fast_slide"?L.T("快滑"):phase=="press"?L.T("按下"):L.T("松开"))+" · "+wave+" · "+c["count"]+L.T(" 条")});}catch{skipped++;}}if(candidateBox.Items.Count>0){candidateBox.SelectedIndex=0;Directory.CreateDirectory(System.IO.Path.Combine(AppPaths.Data,"profiles"));AtomicWrite(System.IO.Path.Combine(AppPaths.Data,"profiles","last-capture.txt"),System.IO.Path.GetFullPath(file));}recordStatus.Text=candidateBox.Items.Count>0?L.T("录制已载入，可保存为命名配置。"):L.T("未取得可用反馈。");if(candidateBox.Items.Count==0 && d.ContainsKey("message"))recordStatus.Text+="\n"+d["message"];}
 void ApplyCandidate(){var c=candidateBox.SelectedItem as Candidate;if(c==null)throw new Exception(L.T("请先选择录制结果。"));var w=new JavaScriptSerializer().Deserialize<WaveSpec>(new JavaScriptSerializer().Serialize(c.Wave));if(eventBox.SelectedIndex==0)CurrentPad.Motion=w;else if(eventBox.SelectedIndex==1)CurrentPad.PressWave=w;else CurrentPad.ReleaseWave=w;LoadWave();ReadEditor();SavePads();Notice(L.T("已填入当前板、当前事件，可直接微调上方参数。"));}
 void CaptureProgress(){if(recorder!=null && recordResult!=null && File.Exists(recordResult+".progress"))try{recordStatus.Text=File.ReadAllText(recordResult+".progress");}catch(IOException){}}
 async void RecordPad(){if(recorder!=null)return;try{CaptureTool("Python");CaptureTool("Parser");ValidatePresetName(recordName.Text);recordingName=recordName.Text.Trim();recordingSide=editedSide;recordingPreset=full.EditingId;RequireDevice();if((((DeviceChoice)deviceBox.SelectedItem).Pid!=0x1303 || ((DeviceChoice)deviceBox.SelectedItem).Transport!="bluetooth" || ((DeviceChoice)deviceBox.SelectedItem).Source=="HID"))throw new Exception(L.T("触觉录制目前仅支持蓝牙连接。"));ReadEditor();SavePads();if(fullTrial)EndFullTrial();Stop();string lab=AppPaths.Capture;Directory.CreateDirectory(AppPaths.Logs);recordResult=System.IO.Path.Combine(AppPaths.Logs,"capture-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".result");string side=sourceBox.SelectedIndex==0?"left":"right";recorder=Process.Start(new ProcessStartInfo(System.IO.Path.Combine(lab,"SC2CaptureWorker.exe"),"--record "+side+" "+Quote(recordResult)+" "+Quote(selectedDevicePath)){UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden});recordButton.IsEnabled=false;stopRecord.IsEnabled=true;recordStatus.Text=L.T("等待管理员提示；录制将按准备、静止、慢滑、快滑、按压进行。");Process active=recorder;await Task.Run(delegate{if(!active.WaitForExit(150000)){File.WriteAllText(recordResult+".stop","stop");throw new Exception(L.T("录制收尾超时，已请求停止，原日志保留。"));}});if(File.Exists(recordResult+".error"))throw new Exception(File.ReadAllText(recordResult+".error"));if(!File.Exists(recordResult))throw new Exception(L.T("录制未产生结果，请查看 logs 文件夹。"));string folder=File.ReadAllText(recordResult).Trim();string python=CaptureTool("Python");recordStatus.Text=L.T("正在解析完整触觉报文…");await Task.Run(delegate{using(var p=Process.Start(new ProcessStartInfo(python,Quote(System.IO.Path.Combine(lab,"auto_capture.py"))+" "+Quote(folder)+" --parser "+Quote(CaptureTool("Parser"))){UseShellExecute=false,CreateNoWindow=true})){if(!p.WaitForExit(120000)){p.Kill();throw new Exception(L.T("分析超时。"));}if(p.ExitCode!=0)throw new Exception(L.T("分析失败，原日志保留。"));}});LoadCandidates(System.IO.Path.Combine(folder,"haptics.json"));CreateRecordedPreset();}catch(Exception e){recordStatus.Text=L.T("录制停止：")+e.Message;}finally{if(recorder!=null){recorder.Dispose();recorder=null;}recordButton.IsEnabled=true;stopRecord.IsEnabled=false;}}
 void StartPadTrial(){StartFullTrial();}
 void UpdateMotionFields(){if(inertiaBox==null)return;bool mouse=actionBox.SelectedIndex==0,scroll=actionBox.SelectedIndex==1;foreach(string k in new[]{"speed","smooth","dragThreshold"})parameterCells[k].Visibility=mouse?Visibility.Visible:Visibility.Collapsed;parameterCells["scroll"].Visibility=scroll?Visibility.Visible:Visibility.Collapsed;parameterCells["reversal"].Visibility=scroll?Visibility.Visible:Visibility.Collapsed;if(scrollDirection!=null){scrollDirectionHost.Visibility=scroll?Visibility.Visible:Visibility.Collapsed;}inertiaBox.Visibility=mouse?Visibility.Visible:Visibility.Collapsed;parameterCells["friction"].Visibility=mouse && inertiaBox.IsChecked==true?Visibility.Visible:Visibility.Collapsed;var visible=new List<FrameworkElement>();foreach(string key in new[]{"speed","smooth","dragThreshold","scroll","reversal","press","release","friction"})if(parameterCells[key].Visibility==Visibility.Visible)visible.Add(parameterCells[key]);int columns=Math.Min(3,visible.Count);motionGrid.ColumnDefinitions.Clear();motionGrid.RowDefinitions.Clear();for(int c=0;c<columns;c++)motionGrid.ColumnDefinitions.Add(new ColumnDefinition());for(int r=0;r<(visible.Count+columns-1)/columns;r++)motionGrid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});for(int i=0;i<visible.Count;i++){Grid.SetColumn(visible[i],i%columns);Grid.SetRow(visible[i],i/columns);}}
 string CleanRecording(string file){string lab=AppPaths.Capture;if(System.IO.Path.GetFileName(file)=="haptics.cleaned.json")file=System.IO.Path.Combine(System.IO.Path.GetDirectoryName(file),"haptics.json");string python=CaptureTool("Python");using(var p=Process.Start(new ProcessStartInfo(python,"-X utf8 "+Quote(System.IO.Path.Combine(lab,"clean_capture.py"))+" "+Quote(file)){UseShellExecute=false,CreateNoWindow=true})){if(!p.WaitForExit(10000)){p.Kill();throw new Exception(L.T("录制筛选超时，原文件保留。"));}if(p.ExitCode!=0)throw new Exception(L.T("无法校验录制动作，未应用此结果；需要原始输入记录。"));}return System.IO.Path.Combine(System.IO.Path.GetDirectoryName(file),"haptics.cleaned.json");}
 bool liveBridge;
}
